// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  signalId: __t.u64().primaryKey().name("signal_id"),
  userPhone: __t.string().name("user_phone"),
  incidentId: __t.option(__t.u64()).name("incident_id"),
  severity: __t.u32(),
  message: __t.string(),
  status: __t.string(),
  timestamp: __t.u64(),
});
