// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  fragmentId: __t.u64().primaryKey().name("fragment_id"),
  incidentId: __t.u64().name("incident_id"),
  eventId: __t.option(__t.u64()).name("event_id"),
  r2Url: __t.string().name("r_2_url"),
  mediaType: __t.string().name("media_type"),
  timestamp: __t.u64(),
});
