// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DemoCounter = __t.object("DemoCounter", {
  id: __t.u32(),
  value: __t.u32(),
});
export type DemoCounter = __Infer<typeof DemoCounter>;

export const DistressSignals = __t.object("DistressSignals", {
  signalId: __t.u64(),
  userPhone: __t.string(),
  incidentId: __t.option(__t.u64()),
  severity: __t.u32(),
  message: __t.string(),
  status: __t.string(),
  timestamp: __t.u64(),
});
export type DistressSignals = __Infer<typeof DistressSignals>;

export const Incidents = __t.object("Incidents", {
  incidentId: __t.u64(),
  category: __t.string(),
  status: __t.string(),
  description: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
});
export type Incidents = __Infer<typeof Incidents>;

export const LiveEntities = __t.object("LiveEntities", {
  id: __t.identity(),
  userPhone: __t.option(__t.string()),
  type: __t.string(),
  subType: __t.string(),
  status: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  lastSeen: __t.u64(),
});
export type LiveEntities = __Infer<typeof LiveEntities>;

export const MediaFragments = __t.object("MediaFragments", {
  fragmentId: __t.u64(),
  incidentId: __t.u64(),
  eventId: __t.option(__t.u64()),
  r2Url: __t.string(),
  mediaType: __t.string(),
  timestamp: __t.u64(),
});
export type MediaFragments = __Infer<typeof MediaFragments>;

export const TimelineEvents = __t.object("TimelineEvents", {
  eventId: __t.u64(),
  incidentId: __t.u64(),
  eventType: __t.string(),
  message: __t.string(),
  timestamp: __t.u64(),
});
export type TimelineEvents = __Infer<typeof TimelineEvents>;

export const Users = __t.object("Users", {
  identity: __t.identity(),
  phone: __t.string(),
  name: __t.option(__t.string()),
  role: __t.string(),
  trustScore: __t.f32(),
});
export type Users = __Infer<typeof Users>;

