// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.identity().primaryKey(),
  entityNumber: __t.u64().name("entity_number"),
  userPhone: __t.option(__t.string()).name("user_phone"),
  type: __t.string(),
  subType: __t.string().name("sub_type"),
  status: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  lastSeen: __t.u64().name("last_seen"),
  destinationLat: __t.option(__t.f64()).name("destination_lat"),
  destinationLng: __t.option(__t.f64()).name("destination_lng"),
});
