// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptDispatchReducer from "../accept_dispatch_reducer";
import AdminAssignDestinationReducer from "../admin_assign_destination_reducer";
import CreateIncidentReducer from "../create_incident_reducer";
import GodModeDeleteEntityReducer from "../god_mode_delete_entity_reducer";
import GodModeDeleteIncidentReducer from "../god_mode_delete_incident_reducer";
import GodModeMoveEntityReducer from "../god_mode_move_entity_reducer";
import LinkUserReducer from "../link_user_reducer";
import RejectDispatchReducer from "../reject_dispatch_reducer";
import ReportDistressReducer from "../report_distress_reducer";
import RequestResponderReducer from "../request_responder_reducer";
import SeedDemoDataReducer from "../seed_demo_data_reducer";
import UpdateLocationReducer from "../update_location_reducer";

export type AcceptDispatchParams = __Infer<typeof AcceptDispatchReducer>;
export type AdminAssignDestinationParams = __Infer<typeof AdminAssignDestinationReducer>;
export type CreateIncidentParams = __Infer<typeof CreateIncidentReducer>;
export type GodModeDeleteEntityParams = __Infer<typeof GodModeDeleteEntityReducer>;
export type GodModeDeleteIncidentParams = __Infer<typeof GodModeDeleteIncidentReducer>;
export type GodModeMoveEntityParams = __Infer<typeof GodModeMoveEntityReducer>;
export type LinkUserParams = __Infer<typeof LinkUserReducer>;
export type RejectDispatchParams = __Infer<typeof RejectDispatchReducer>;
export type ReportDistressParams = __Infer<typeof ReportDistressReducer>;
export type RequestResponderParams = __Infer<typeof RequestResponderReducer>;
export type SeedDemoDataParams = __Infer<typeof SeedDemoDataReducer>;
export type UpdateLocationParams = __Infer<typeof UpdateLocationReducer>;

