// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import IncrementCounterReducer from "../increment_counter_reducer";
import UpdateLocationReducer from "../update_location_reducer";

export type IncrementCounterParams = __Infer<typeof IncrementCounterReducer>;
export type UpdateLocationParams = __Infer<typeof UpdateLocationReducer>;

